# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66e827a9b48d63a4e6a327330a814e1e"
name = "admin-action-extension"
handle = "admin-action-extension-12"
application_url = "https://vbulletin-hart-racks-bomb.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders"

[auth]
redirect_urls = [
  "https://vbulletin-hart-racks-bomb.trycloudflare.com/auth/callback",
  "https://vbulletin-hart-racks-bomb.trycloudflare.com/auth/shopify/callback",
  "https://vbulletin-hart-racks-bomb.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
